# Generated by Django 2.2.28 on 2026-02-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20260201_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(default='https://example.com/'),
            preserve_default=False,
        ),
    ]
