# Generated by Django 2.2.28 on 2026-02-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(default='https://example.com/'),
        ),
    ]
